name: 'deploy webiste and ebooks'

on:
  push:
    branches:
      - main # branch name to trigger deployment

jobs:
  job_deploy_website:
    name: 'deploy website'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Installing 
      run: npm install honkit --save-dev

    - name: Build
      run: |
        npx honkit build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      # If you're changing the branch from main,
      # also change the `main` in `refs/heads/main`
      # below accordingly.
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./_book

  job_deploy_ebooks:
    name: 'deploy ebooks'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Installing 
      run: npm install honkit --save-dev

    - name: Installing Prerequisite 
      run: |
        npm install honkit --save-dev
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx
        sudo apt-get install -y ocl-icd-opencl-dev

    - name: 'Installing calibre'
      run: |
        sudo -v
        wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin
    
    - name: 'Preparing for ebooks generations'
      run: |
        npx honkit build

    - name: 'Make folder ebooks'
      run: |
        cd _book
        mkdir ebooks
        ls -a
        cd ../

    - name: 'Generating ebook in pdf'
      run: npx honkit pdf ./ ./_book/ebooks/ebook${{ env.EBOOK_NAME }}.pdf
    - name: 'Generating ebook in epub'
      run: npx honkit epub ./ ./_book/ebooks/ebook${{ env.EBOOK_NAME }}.epub
    - name: 'Generating ebook in mobi'
      run: npx honkit mobi ./ ./_book/ebooks/ebook${{ env.EBOOK_NAME }}.mobi
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      # If you're changing the branch from main,
      # also change the `main` in `refs/heads/main`
      # below accordingly.
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./_book